# Generated by Django 4.1.5 on 2023-01-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('From Person', 'From Person'), ('From hees', 'From Hees')], default='From Person', max_length=50),
        ),
    ]
